name: Veracode Build
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.repository }}
    steps:
    - name: Package the application
      id: application_package
      run: |
        curl -sSO https://tools.veracode.com/veracode-cli/veracode-cli_2.23.0_linux_x86.tar.gz
        tar -xvf veracode-cli_2.23.0_linux_x86.tar.gz
        mv veracode-cli_2.23.0_linux_x86 cli
        ./cli/veracode package --source . --output veracode-artifacts --trust
        zip veracode-artifact.zip veracode-artifacts/* -x .zip .tar .tar.gz .gz

    - name: Package error
      if: failure() && steps.application_package.outcome == 'failure'
      run: |
        echo "::error::Veracode static scan faced a problem. Please contact your Veracode administrator for more information."

