name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v2"

      - name: Run YAML to Github Output Action
        id: yaml-output
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: ./veracode.yml
          main_key: veracode_image
        
      - name: Print Variables
        run: |
          echo "Cluster Name: ${{ steps.yaml-output.outputs.imageName }}"
  test1:
    needs: test
    uses: ./.github/workflows/buildVeracode.yml
    with:
           repository: veracode/scm-packaging:2.1.0
     
