name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    runs-on: "ubuntu-22.04"
    outputs:
      pr-number: ${{ steps.yaml-output.outputs.imageName }}
    steps:
      - uses: "actions/checkout@v2"

      - name: Build docker images
        run: docker build -t local < .devcontainer/Dockerfile

      - name: Run YAML to Github Output Action
        id: yaml-output
        uses: christian-ci/action-yaml-github-output@v2
        with:
          file_path: ./veracode.yml
          main_key: veracode_image
        
      - name: Print Variables
        run: |
          echo "Cluster_Name=${{ steps.yaml-output.outputs.imageName }}" >> $GITHUB_OUTPUT
  test1:
    needs: test
    uses: ./.github/workflows/buildVeracode.yml
    with:
           repository: .devcontainer/Dockerfile
     
